/**
 * ============================================================
 *  CONTRACT TESTING (Provider)  —  pact/provider.test.js
 * ============================================================
 *
 *  CONCEPT — Provider Verification
 *  ----------------------------------
 *  The Provider side reads the contract generated by the consumer
 *  and verifies that the REAL API (your Lambda) honours it.
 *
 *  This runs separately — typically:
 *    • On the Lambda repo's CI pipeline when Lambda code changes
 *    • Or in a scheduled job that verifies contracts haven't broken
 *
 *  If the Lambda team changes the response shape (e.g., renames
 *  "message" to "status"), this verification will FAIL and alert
 *  both teams BEFORE the change reaches production.
 *
 *  That's the power of contract testing — decoupled, fast,
 *  no environment coordination needed.
 *
 * ============================================================
 */

const { VerifierV3 } = require('@pact-foundation/pact');
const path = require('path');

describe('ContactLambda — Provider Contract Verification', () => {

  it('validates the contract against the real Lambda endpoint', () => {
    const verifier = new VerifierV3({
      provider: 'ContactLambda',
      providerBaseUrl: 'https://mwtufj8xia.execute-api.ca-central-1.amazonaws.com',

      // Load the contract file generated by the consumer test
      pactUrls: [
        path.resolve('pact/pacts/PortfolioFrontend-ContactLambda.json'),
      ],

      // ── Provider States ────────────────────────────────────
      // "Provider states" set up the backend to be in the right
      // condition for each interaction. For a stateless Lambda
      // you may not need any — but this pattern is essential
      // when testing stateful backends (databases, queues, etc.)
      stateHandlers: {
        'Lambda is healthy and accepting submissions': async () => {
          // In a real scenario: seed a test database, reset mocks, etc.
          console.log('Provider state: Lambda is ready');
        },
      },

      // Publish verification results back to Pact Broker (optional)
      // publishVerificationResult: true,
      // providerVersion: process.env.GIT_SHA || '1.0.0',

      // Timeout for each interaction verification (Lambda cold starts can be slow)
      timeout: 30000,

      logLevel: 'warn',
    });

    return verifier.verifyProvider();
  });

});

/**
 *  ── How to run provider verification ──────────────────────
 *
 *  1. Run consumer tests first to generate the pact file:
 *       npx jest pact/consumer.contact.test.js
 *
 *  2. Then verify the provider:
 *       npx jest pact/provider.test.js
 *
 *  ── What to tell a Deloitte interviewer ──────────────────
 *
 *  "I implemented consumer-driven contract testing using Pact.
 *   The frontend defines what it expects from the Lambda API,
 *   and a JSON contract is generated. Both sides are tested
 *   independently — no live environment needed for the consumer
 *   tests. This catches breaking API changes before deployment
 *   and replaces fragile integration tests with fast, reliable
 *   unit-level contract verification."
 */
